In [13]:
import pandas as pd

studenti = {
    "nome": ["Mario", "Rudy", "Marco", "Andrea", "Saverio",  "Giulia", "Fabrice", "Laura", "Luigia", "Teresa"],
    "cognome": ["Ricci", "Botosso", "Secci", "Romano","Carulli", "Pierro", "Cheick", "Ricordi", "Valente", "Balsamo"],
    "email": ["mario.ricci@example.com", "rudy.botosso@example.it","marco.secci@example.com",
    "andrea.romani@example,com", "saverio.carulli@example.com", "giulia.pierro@example.com", "fabrice.cheick@example.com",
     "laura.ricordi@example.com", "luigia.valente@example.com", "teresa.balsamo@example.com"],
    "eta" : [30, 54, 54, 36, 34, 25, 51, 35, 32, 25],
    "citta" : ["Milano", "Biella", "San Don di Piave", "Ripatransone", "Spinazzola", "Latina", "Ferrara", "Alessandria", "Avellino", "Roma"],
    "voto": [8, 9, 7, 6, 9, 10, 8, 9, 7, 7],
    "stipendio": [2000, 3000, 1500, 2500, 3000, 2000, 2200, 1900, 2000, 2500]
}

#chiama pandas e crea un dataframe dal dictionary studenti
df = pd.DataFrame(studenti)
df #stampa il dataframe tipo tabella divero  da print dove lo mette in formato csv

,nome,cognome,email,eta,citta,voto,stipendio
0,Mario,Ricci,mario.ricci@example.com,30,Milano,8,2000
1,Rudy,Botosso,rudy.botosso@example.it,54,Biella,9,3000
2,Marco,Secci,marco.secci@example.com,54,San Don di Piave,7,1500
3,Andrea,Romano,"andrea.romani@example,com",36,Ripatransone,6,2500
4,Saverio,Carulli,saverio.carulli@example.com,34,Spinazzola,9,3000
5,Giulia,Pierro,giulia.pierro@example.com,25,Latina,10,2000
6,Fabrice,Cheick,fabrice.cheick@example.com,51,Ferrara,8,2200
7,Laura,Ricordi,laura.ricordi@example.com,35,Alessandria,9,1900
8,Luigia,Valente,luigia.valente@example.com,32,Avellino,7,2000
9,Teresa,Balsamo,teresa.balsamo@example.com,25,Roma,7,2500

Filtri in pandas

In [6]:
df[df["stipendio"] > 2000]

      nome  cognome  eta         citta  voto  stipendio
1     Rudy  Botosso   54        Biella     9       3000
3   Andrea   Romano   36  Ripatransone     6       2500
4  Saverio  Carulli   34    Spinazzola     9       3000
6  Fabrice   Cheick   51       Ferrara     8       2200
9   Teresa  Balsamo   25          Roma     7       2500

In [9]:
#stipendio di un nome specifico 
#select stipendio from studenti where nome = 'Fabrice'
df[df["stipendio"] <=  2200][['nome', 'cognome', 'stipendio']]

      nome  cognome  stipendio
0    Mario    Ricci       2000
2    Marco    Secci       1500
5   Giulia   Pierro       2000
6  Fabrice   Cheick       2200
7    Laura  Ricordi       1900
8   Luigia  Valente       2000

In [17]:
df[df['email'].str.endswith('.it')]
df[df['email'].str.contains('to')]

   nome  cognome                    email  eta   citta  voto  stipendio
1  Rudy  Botosso  rudy.botosso@example.it   54  Biella     9       3000