## Le condizioni
- AND
- NOT
- OR

In [5]:
import pandas as pd

studenti = {
    "nome": ["Mario", "Rudy", "Marco", "Andrea", "Saverio",  "Giulia", "Fabrice", "Laura", "Luigia", "Teresa"],
    "cognome": ["Ricci", "Botosso", "Secci", "Romano","Carulli", "Pierro", "Cheick", "Ricordi", "Valente", "Balsamo"],
    "email": ["mario.ricci@example.com", "rudy.botosso@example.it","marco.secci@example.com",
    "andrea.romani@example,com", "saverio.carulli@example.com", "giulia.pierro@example.com", "fabrice.cheick@example.com",
     "laura.ricordi@example.com", "luigia.valente@example.com", "teresa.balsamo@example.com"],
    "eta": [30, 54, 54, 36, 34, 25, 51, 35, 32, 25],
    "citta": ["Milano", "Biella", "San Don di Piave", "Ripatransone", "Spinazzola", "Latina", "Ferrara", "Alessandria", "Avellino", "Roma"],
    "voto": [8, 9, 7, 6, 9, 10, 8, 9, 7, 7],
    "stipendio": [2000, 3000, 1500, 2500, 3000, 2000, 2200, 2900, 2000, 2500],
    "ruolo": ["Sviluppatore", "Project Manager", "Junior Editor", "Commercial Manager", "Analista", "R&d  Manager", "Back Office", "Hr Manager", "Data Analyst Senior","Marketing Officer"] 
}

#chiama pandas e crea un dataframe dal dictionary studenti
df = pd.DataFrame(studenti)
df #stampa il dataframe tipo tabella divero  da print dove lo mette in formato csv

,nome,cognome,email,eta,citta,voto,stipendio,ruolo
0,Mario,Ricci,mario.ricci@example.com,30,Milano,8,2000,Sviluppatore
1,Rudy,Botosso,rudy.botosso@example.it,54,Biella,9,3000,Project Manager
2,Marco,Secci,marco.secci@example.com,54,San Don di Piave,7,1500,Junior Editor
3,Andrea,Romano,"andrea.romani@example,com",36,Ripatransone,6,2500,Commercial Manager
4,Saverio,Carulli,saverio.carulli@example.com,34,Spinazzola,9,3000,Analista
5,Giulia,Pierro,giulia.pierro@example.com,25,Latina,10,2000,R&d Manager
6,Fabrice,Cheick,fabrice.cheick@example.com,51,Ferrara,8,2200,Back Office
7,Laura,Ricordi,laura.ricordi@example.com,35,Alessandria,9,2900,Hr Manager
8,Luigia,Valente,luigia.valente@example.com,32,Avellino,7,2000,Data Analyst Senior
9,Teresa,Balsamo,teresa.balsamo@example.com,25,Roma,7,2500,Marketing Officer

In [7]:
#AND
df[(df["stipendio"] > 2000) & (df["stipendio"] <4000)][['nome', 'cognome', 'stipendio']]

      nome  cognome  stipendio
1     Rudy  Botosso       3000
3   Andrea   Romano       2500
4  Saverio  Carulli       3000
6  Fabrice   Cheick       2200
7    Laura  Ricordi       2900
9   Teresa  Balsamo       2500

In [9]:
#or

df[(df['stipendio'] >= 2000) & (df['stipendio'] <= 3000) & (df['ruolo'] == 'Sviluppatore')]

,nome,cognome,email,eta,citta,voto,stipendio,ruolo
0,Mario,Ricci,mario.ricci@example.com,30,Milano,8,2000,Sviluppatore